### ISSUE TITLE
Query string parameters gets sorted

### ISSUE THREAD

**Issue by CasiOo** [aurelia/path#14]
This isn't a bug, but what's the reasoning behind sorting the query string parameters when building it?
https://github.com/aurelia/path/blob/master/src/index.js#L118

Sorting them seems unnecessary to me. Is it just to make any test case happy? `Object.keys` return the keys in arbitrary order, so are they just sorted to make the assertions in tests easier to implement?

A guy in chat had a scenario, where he wanted to control the parameter ordering. He wanted the search query key to come first `q=some-search`. This should be possible, if the keys weren't being sorted. Usually the browsers will return the keys in the order they were declared on the object like:
```
//b will be printed before a
var obj = {b:1, a:2, c:3};
    
for (var prop in obj) {
  console.log("obj." + prop + " = " + obj[prop]);
}
```
I know you can't count on the browsers to act this way given the documentation.

**Comment by bryanrsmith** [comment]
Interesting. I don't know the reason, but it appears to date back to the initial commit in the route-recognizer project.

https://github.com/aurelia/route-recognizer/commit/0230e970ffffc79885eab14721f8535848948ada#diff-45cdbfd3b88db493b262a4df7bb11d88R369

**Comment by zenbaku** [comment]
One reason I can come up for query parameters sorting is browser caching. I don't know if it applies in this specific context, but it is usually a good practice.

**Comment by EisenbergEffect** [comment]
Closing since this isn't really an issue.
