### ISSUE TITLE
Builded query string doesn't match rfc standard

### ISSUE THREAD

**Issue by fragsalat** [aurelia/path#21]
**I'm submitting a bug report**

* **Library Version:**
1.0.0

**Please tell us about your environment:**
* **Operating System:**
Ubuntu 16.10

* **Node Version:**
6.3.1

* **NPM Version:**
3.10.3

* **JSPM OR Webpack AND Version**
JSPM 0.16.42

* **Browser:**
all

* **Language:**
all

**Current behavior:**
If you pass an object, which contains an array, to buildQueryString function, it returns a not standard conform query string.
Current result:
`decodeURIComponent(buildQueryString({list: [1, 2, 3]})) === 'list[]=1&list[]=2&list[]=3'`

**Expected/desired behavior:**
In the RFC 6570 standard for URI templates is written that an array parameter has no braces but is just repeated multiple times.
https://tools.ietf.org/html/rfc6570#section-3.2.8

Therefor the check in buildParam (https://github.com/aurelia/path/blob/master/src/index.js#L125)
for Arrays there should be a key without braces. 
The correct result should be:
`decodeURIComponent(buildQueryString({list: [1, 2, 3]})) === 'list=1&list=2&list=3'`

Correct me if I'm wrong of if I misunderstood anything.

**Comment by stsje** [comment]
Aurelia follows the most modern way of building parameters. What you are looking for is the traditional way of building query parameters. JQuery mentions it in their docs with an explanation http://api.jquery.com/jQuery.param/

It would be nice with an option to toggle which style you want. Think I have mentioned it earlier, maybe even opened an issue about it in one of the repositories.

**Comment by stsje** [comment]
Some server side technologies don't yet support the modern syntax, so it would definitely be a good idea with the traditional option.

**Comment by fragsalat** [comment]
Am I correct that the old standard doesn't support nested parameters in the URI template?
I couldn't find any suiting solution with the old standard to render a query with the following parameters.
`{list: [{a: 1, b: 2}, {a: 1, c: 3}]}`
In the new style they result in the following query `?list[0][a]=1&list[0][b]=2&list[1][a]=1&list[1][c]=3`.
Since the old standard seem to have no way to declare a key of an value it is not possible to just render the same parameter list in two different styles.
If I follow the standard the representation of the parameters would be `?foo={"bar":1}&foo={"houses":2}&foo={"green":3}`
The JavaScript representation (without serializing into json string) would be `?foo=[object Object]&foo=[object Object]&foo=[object Object]`
I think we or you don't want that implementation like that or?


Please correct me if I'm wrong or if you have different opinion.

**Comment by stsje** [comment]
The traditional style doesn't serialize deep/complex objects.

Both styles should be supported since some server side technologies don't yet support the more modern style.

**Comment by fragsalat** [comment]
Actually I couldn't find a reference where is mentioned that if a parameter is repeated, it will be overwritten like described here https://github.com/aurelia/path/blob/master/src/index.js#L176
The rfc standard describes that a multiple mentioned parameter creates a list of values.

Therefore I think the isPrimitive check is obsolete and can be removed to ensure the parseQueryString function is able to parse both styles.

Can I remove it or do you have any reference that gives this a reason to stay?

**Comment by EisenbergEffect** [comment]
Fixed.
