### ISSUE TITLE
Latest v1.1.4 didnot update dist files.

### ISSUE THREAD

**Issue by 3cp** [aurelia/path#37]
**I'm submitting a bug report**
**I'm submitting a feature request**

* **Library Version:**
1.1.4

**Please tell us about your environment:**
* **Operating System:**
All

* **Node Version:**
N/A

* **NPM Version:**
N/A

* **JSPM OR Webpack AND Version**
N/A

* **Browser:**
all
* **Language:**
all

**Current behavior:**

dist files are same as old 1.1.3.

**Expected/desired behavior:**

* **What is the expected behavior?**

To update dist files with 1.1.4 source changes.

* **What is the motivation / use case for changing the behavior?**

**Comment by 3cp** [comment]
Correction, @EisenbergEffect. The dist files in this repo are updated, but npm package 1.1.4 has wrong dist files.

**Comment by 3cp** [comment]
OK, I saw you committed latest dist file in the last commit of 1.1.5. Please release 1.1.5.

**Comment by EisenbergEffect** [comment]
Released!

**Comment by 3cp** [comment]
Thx! It finally works with the **plugin skeleton** in dumber I am working on.

Dumber supports `.use.feature('../src')` which is more intuitive than `.use.feature('resources')` with  a requirejs path config: `"resources": "../src"`.

`.use.feature('../src')` could not work in CLI bundler because RequireJS/SystemJS doesn't support module id starting with `../`.
